name: Create Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        run: chmod +x ./gradlecw
      - name: build
        run: ./gradlecw build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            FPFabric/build/libs/*
            FPForge/build/libs/*
      - name: Publish-Forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 333287
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}  
          loaders: forge
          game-versions: |
            1.19
            1.19.1
            1.19.2
          name: ${{github.ref_name}} - Forge
          version-type: beta
          files: '*Forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-Forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: H5XMjpHi
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          game-versions: |
            1.19
            1.19.1
            1.19.2
          name: ${{github.ref_name}} - Forge
          files: '*Forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-Fabric
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: H5XMjpHi
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 333287
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}  
          loaders: fabric
          game-versions: |
            1.19
            1.19.1
            1.19.2
          name: ${{github.ref_name}} - Fabric
          files: '*Fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
